[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wordllama"
version = "0.1.0"
description = "WordLlama Embedding and Training"
readme = { file = "README.md", content-type = "text/markdown" }
license = { text = "MIT" }
requires-python = ">=3.8"
authors = [{ name = "Lee Miller", email = "dleemiller@gmail.com" }]
dependencies = [
  "numpy",
  "safetensors",
  "tokenizers",
  "toml",
  "pydantic>=2"
]

[project.optional-dependencies]
train = [
  "accelerate",
  "torch>=2",
  "transformers>=4",
  "sentence-transformers",
  "datasets",
  "nltk",
]

[project.urls]
Homepage = "https://github.com/dleemiller"
Repository = "https://github.com/dleemiller/WordLlama"

[project.scripts]
wordllama = "wordllama.wordllama:main"

[tool.setuptools.package-data]
wordllama = ["**/*.toml", "tokenizers/*.json"]

[tool.setuptools.dynamic]
classifiers = { file = "classifiers.txt" }

